### ISSUE TITLE
Bring back TrueNAS guides

### ISSUE THREAD

**Issue by TheDevMinerTV** [truecharts/website#792]
### Is your feature request related to a problem?

I'm trying to install borg-server right now on my TrueNAS instance and the only place that has a working Helm chart is here. The docs for adding TrueCharts to TrueNAS seems to have been removed though.
![image](https://github.com/user-attachments/assets/88c478e1-7cfb-493c-829e-3de3d5024bdd)
This is super frustrating. :/

### Describe the solution you'd like

Bring back at least the instructions that say "Removed as SCALE is deprecated."

### Describe alternatives you've considered

Trying to set up borg via container myself, but I'd rather to use a "1 click install" because this is unnecessarily complex.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by nintendoeats** [comment]
I'd like to add, I DID find the documentation for adding TrueCharts to TrueNAS scale and found that they did not work. If this is not supported, please remove these instructions or add a note saying that support is deprecated!

https://irgendwr.github.io/truecharts-apps/manual/Quick-Start%20Guides/01-Adding-TrueCharts/

**Comment by bitpushr** [comment]
@TheDevMinerTV It wasn't my call to make, but the SCALE apps catalogue, project-specific tooling related to SCALE, and virtually everything else to do with SCALE has been removed from our end. If you already have our SCALE catalogue on your system, you can install borg-server like you normally would any other app/chart (though we don't advise you to do so). If you don't have the catalogue on your system, there's not currently a simple way to re-add it and thus, not a way to install any of our apps on a SCALE system.

Our GitHub does have a repo with an archived version of the SCALE catalogue as it was prior to removal, but it's nothing you can just fork and then add into SCALE; you'd need a working CI/backend to build it into something usable. One last option would be to use the Custom App button within SCALE and deploy an app/chart that way. I haven't done this myself, but I know other people in our Discord have used this to re-deploy their apps and allow them to be updated. SCALE -> Apps -> Discover Apps -> Custom App.

This is all intentional, as was iX's decision to rip Kubernetes out of SCALE come ElectricEel without giving anyone notice they were doing so. This was after we (as a project) put a lot of effort into the Cobia -> DragonFish migration process, and after iX agreed to our request to have OpenEBS removed from SCALE itself, and users forced to instead install it from our catalogue, due to issues with the version SCALE shipped with. Despite knowing these works were happening, they proceeded anyway without any notice.

You're welcome to use the WaybackMachine's [archive](https://web.archive.org/web/20240604140854/https://truecharts.org/deprecated/scale/) of our docs to see what the process was/is like, but again, it's functionally useless if you don't already have our catalogue added.

**Comment by bitpushr** [comment]
@nintendoeats That's not the documentation. I don't know that that documentation is, but I've never seen it before. It's also very old, having been last updated in 2021.

Our docs have existed on our [website]( https://truecharts.org/general/) for as long as I can remember. As above, though, it's no longer possible to add our catalogue to SCALE systems.

**Comment by bitpushr** [comment]
Closing
